name: Threefold_io
on: 
  push:
    branch: [ zola_development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www3.threefold.io
      uses: appleboy/ssh-action@master
      with:
        host: www3.threefold.io
        username: root
        key: ${{ secrets.TF_SECRET }}
        port: 22
        script: |
          cd /opt/www_threefold_io/
          git pull
          git log -1
          git status
