name: www2.threefold_io
on: 
  push:
    branches: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.threefold.io
      uses: appleboy/ssh-action@master
      with:
        host: www2.threefold.io
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 30422
        script: |
          cd websites/www2/www_threefold_io/
          git log -1
          git fetch
          git reset --hard origin/development
          sed -i "s/https:\/\/www.threefold.io/https:\/\/www2.threefold.io/g" config.toml
          ./build.sh
          
